### ISSUE TITLE
env.py: ISIS_PATH in new location as of ISIS 3.6.0

### ISSUE THREAD

**Issue by dpmayerUSGS** [wtolson/pysis#23]
The location of the ISIS bin directory changed as of ISIS 3.6.0 to `ISIS_ROOT/install/bin`, but `env.py` assumes it is `ISIS_ROOT/bin`. This prevents pysis from importing isis

Running pysis 0.6.1 from conda-forge:
```
import pysis.env
pysis.env.ISIS_ROOT
>'/usgs/pkgs/isis3.6.2/isis'
pysis.env.ISIS_PATH
> '/usgs/pkgs/isis3.6.2/isis/bin'

from pysis import isis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pds2010mgr/anaconda3/envs/PDS-Services/lib/python3.6/site-packages/pysis/isis.py", line 39, in <module>
    strict=(ISIS_VERSION is not None),
  File "/home/pds2010mgr/anaconda3/envs/PDS-Services/lib/python3.6/site-packages/pysis/isis.py", line 24, in __init__
    super(ModuleWrapper, self).__init__(**kwargs)
  File "/home/pds2010mgr/anaconda3/envs/PDS-Services/lib/python3.6/site-packages/pysis/isiscommand.py", line 68, in __init__
    self._setup_commands()
  File "/home/pds2010mgr/anaconda3/envs/PDS-Services/lib/python3.6/site-packages/pysis/isiscommand.py", line 71, in _setup_commands
    for name, cmd in self._get_commands():
  File "/home/pds2010mgr/anaconda3/envs/PDS-Services/lib/python3.6/site-packages/pysis/isiscommand.py", line 78, in _get_commands
    for name in os.listdir(self._path):
FileNotFoundError: [Errno 2] No such file or directory: '/usgs/pkgs/isis3.6.2/isis/bin'
```

I think it would be helpful if `env.py` included some logic to either set `ISIS_PATH` based on the ISIS version number (>=3.6 has `bin` in new location) or maybe look for an environment variable $ISISPATH first like it does for $ISISROOT, but set a default if it's undefined. The second option is probably easier to maintain.

**Comment by dpmayerUSGS** [comment]
Oops!
Solution is actually to change how `$ISISROOT`is defined if using versions >=3.6.
Beginning with 3.6.0, `$ISISROOT` should be set to `/your/path/install` rather than `/your/path/isis`
